parser: babel-eslint

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings

plugins:
  - import

settings:
  import/ignore:
    - node_modules                          # mostly CommonJS (ignored by default)
    - \.coffee$                             # fraught with parse errors
    - \.(scss|less|css)$                    # can't parse unprocessed CSS modules, either
    - \.(jpe?g|png|gif|ico)$                # can't parse images
    - \.svg(\?v=\d+.\d+.\d+)?$              # can't parse images
    - \.eot(\?v=\d+.\d+.\d+)?$              # can't parse fonts
    - \.(woff|woff2|ttf(\?v=\d+.\d+.\d+)?)$ # can't parse fonts
  import/resolver:
    node:
      extensions:
        - .js
      moduleDirectory:
        - node_modules
        - src

parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    classes: true
    jsx: true
    experimentalObjectRestSpread: true

env:
  es6: true
  browser: true
  node: true
  jquery: true
  mocha: true

rules:
  array-bracket-spacing: 2
  array-callback-return: 1
  arrow-body-style: 1
  arrow-parens: 0
  arrow-spacing: 1
  brace-style: 1
  camelcase: 2
  comma-dangle: [1, always-multiline]
  comma-style: 2
  dot-notation: 1
  eol-last: 0
  eqeqeq: 2
  import/imports-first: 1
  import/no-mutable-exports: 1
  import/prefer-default-export: 2
  indent: [2, tab]
  keyword-spacing: 1
  max-len: [2, { "code": 140, "comments": 100 }]
  new-cap: 1
  newline-after-var: 1
  newline-before-return: 1
  newline-per-chained-call: 2
  no-whitespace-before-property: 2
  no-alert: 0
  no-array-constructor: 2
  no-case-declarations: 2
  no-confusing-arrow: [1, {allowParens: true}]
  no-console: 1
  no-const-assign: 1
  no-debugger: 1
  no-dupe-class-members: 2
  no-duplicate-imports: 1
  no-iterator: 1
  no-lone-blocks: 0
  no-loop-func: 2
  no-nested-ternary: 2
  no-param-reassign: 1
  no-trailing-spaces: 0
  no-underscore-dangle: 2
  no-unneeded-ternary: 2
  no-useless-concat: 1
  no-useless-constructor: 1
  no-useless-escape: 1
  no-var: 1
  no-new-object: 1
  object-curly-spacing: [1, always]
  object-shorthand: 1
  one-var: [2, never]
  padded-blocks: [2, never]
  prefer-arrow-callback: 1
  prefer-const: 1
  prefer-rest-params: 1
  prefer-template: 1
  quote-props: [2, as-needed]
  quotes: [2, single]
  semi: [1, always]
  space-before-blocks: 1
  space-in-parens: [2, never]
  space-infix-ops: 1
  template-curly-spacing: [1, never]

globals:
